services:
- docker
script: docker-compose run test
notifications:
  slack:
    secure: lMz1+ged9sonDLLNWkDGUUpPs7rv0W+fDN/LZxgxHaAu+gctUs7DwOEiDC56v5Vr5T66i0jY3CeOEIME6V8ShegP69ZHM0IucWrGD7+nAsPHvZLLQgy4/3QzSze0ujtj/jU6P+AgmarK4K6FW9ReYiAkmwmsbaoE0lOUTtLCU2X7WPU7QjuxjW5sLhzHAG5l51L6XxI8+eCCLOEDBgTen/Hd2OihcxGFi7994YEU0Y4aEKye64glkgo71EAwScPsBVkCIiyC0jiWe8EKsFxdUCXn5Ij1b2p0kjS8HAUfL2w+xM+h82/pTG2uklLWf+/OD7Ol8m3UL8AXVJwicrLUd2ksXSwIljRbujuErOzuGtm8mLyVcl6lyGZgiG53KQza/oIqrmbkHZtvDbl/BSrbeJNEDSUx/A1pT2MHBVJ55TE9eaoIdS6mSK6RAZKQJxsUY70GNfyXIZbWtbDR7RnnoOxiB/8FVcEXfFcwQT0LfoFpdMTdJwcoaRGf+8rkwu+I69uPQiM8OJn1311xb+pOt4vR2wjud31w3gzcFc5+Y0eJmaxeuIdv74jYLHQzYcyheIa9g2HDUzWltOCFe9b0fZgrWgkNYJ+eIcYguEojPa2GW+CQSk3QXtpViyyanAcCGPLnNrGwwgf/vy94yYyqPPgV7464rl/sjOT1+lvRTLs=
