version: '3'
services:
  test:
    build: .
    command: 'npm run test:docker:ci'
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/windbreaker
      - /usr/windbreaker/node_modules
  postgres:
    image: 'postgres:9.6.3-alpine'
    ports:
      - 5432
  rabbitmq:
    image: 'rabbitmq:3.6.10-alpine'
    ports:
      - 5672
