version: '3'
services:
  postgres:
    image: 'postgres:9.6.3-alpine'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rafakato/rabbitmq-delayed-message-exchange'
    ports:
      - '5672:5672'
