version: '3'
services:
  windbreaker:
    # set image tag for builds
    image: windbreaker/windbreaker
    build: .
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/windbreaker
      - /usr/windbreaker/node_modules
    environment:
      SERVICE_ENVIRONMENT: 'docker'
  postgres:
    image: 'postgres:9.6.3-alpine'
    ports:
      - 5432
  rabbitmq:
    image: 'rabbitmq:3.6.10-alpine'
    ports:
      - 5672
