# Address for rabbitmq
amqUrl: amqp://rabbitmq

knex:
  client: 'pg'
  connection:
    host: 'postgres'
    user: 'postgres'
    password: 'postgres'
    database: 'windbreaker_core'
  debug: true
  migrations: 
    tableName: 'migrations'
